/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bibliomvc;

import com.mycompany.bibliomvc.Controller.BookController;
import com.mycompany.bibliomvc.model.Book;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author FRELIANNYSISMELIALOP
 */
public class libery extends javax.swing.JFrame {

 DefaultListModel<String> model = new DefaultListModel<>();
    
    
    
    
    /**
     * Creates new form libery
     */
    public libery() {
        initComponents();
      liberylist.setModel(model);
       updateList();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        liberylist = new javax.swing.JList<>();
        TitleField = new javax.swing.JTextField();
        AuthorField = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();
        YearField = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnSeach = new javax.swing.JButton();
        Updadebtn = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(liberylist);

        TitleField.setText("title");

        AuthorField.setText("Author");

        PriceField.setText("Price");

        YearField.setText("Year");

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnSeach.setText("Seach");
        btnSeach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeachActionPerformed(evt);
            }
        });

        Updadebtn.setText("update");
        Updadebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdadebtnActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Updadebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnadd)
                        .addGap(76, 76, 76)
                        .addComponent(btnSeach))
                    .addComponent(YearField)
                    .addComponent(PriceField)
                    .addComponent(AuthorField)
                    .addComponent(TitleField))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(TitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(YearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnSeach))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Updadebtn)
                    .addComponent(btnDelete))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
       String title = TitleField.getText();
        String author = AuthorField.getText();
        String price = PriceField.getText();
        String year = YearField.getText();

        BookController.addBook(title, author, price, year);
        updateList();
     
      // BookController.addBook(myBook);
       
    }//GEN-LAST:event_btnaddActionPerformed

    private void UpdadebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdadebtnActionPerformed
   String title = TitleField.getText();
        String author = AuthorField.getText();
        String price = PriceField.getText();
        String year = YearField.getText();
        
        
        int selectedIndex = liberylist.getSelectedIndex();

        if (selectedIndex != -1) {
            Book selectedBook = BookController.getBookByIndex(selectedIndex);

            if (selectedBook != null) {
                int id = selectedBook.getId();
                BookController.updateBook(id, title, author, price, year);
                JOptionPane.showMessageDialog(this, "Book was updated.");
                updateList();

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a book to update.");
        }
       

        // TODO add your handling code here:
    }//GEN-LAST:event_UpdadebtnActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
   int selectedIndex = liberylist.getSelectedIndex();
        if (selectedIndex != -1) {
            Book selectedBook =  BookController.getBookByIndex(selectedIndex);

            if (selectedBook != null) {
                int id = selectedBook.getId();
                BookController.deleteBookById(id); // this method below
                JOptionPane.showMessageDialog(this, "Book was deleted.");
                updateList();

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a book to delete.");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeachActionPerformed
   String title = TitleField.getText();
   String bookFound = BookController.searchBook(title);
   model.clear();
   model.addElement(bookFound);
    }//GEN-LAST:event_btnSeachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(libery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(libery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(libery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(libery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new libery().setVisible(true);
            }
        });
    }
     
    public void updateList(){
    model.clear(); 
    ArrayList<String> books = BookController.loadBooks();
     
            for(String book : books){
    
    model.addElement(book);
    }
    
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AuthorField;
    private javax.swing.JTextField PriceField;
    private javax.swing.JTextField TitleField;
    private javax.swing.JButton Updadebtn;
    private javax.swing.JTextField YearField;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSeach;
    private javax.swing.JButton btnadd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> liberylist;
    // End of variables declaration//GEN-END:variables
}
